version: "3.9"

services:
  dummy_gin_db:
    image: postgres
    container_name: dummy_gin_db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: somefatguy
      POSTGRES_DB: defaultdb
    volumes:
      # Create the entities automatically if the database doesn't exist.
      - ./scripts/:/docker-entrypoint-initdb.d
      - testvolume:/var/lib/postgresql/data

volumes:
  testvolume:
